apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "kibana.fullname" . }}
  namespace: default
  labels:
    app: {{ template "kibana.name" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "kibana.name" . }}
  template:
    metadata:
      name: {{ template "kibana.name" . }}
      labels:
        app: {{ template "kibana.name" . }}
      annotations:
        networks: '[
        { "name": "{{  .Values.networks.overlay }}" }
      ]'
    spec:
      containers:
      - name: kibana
        imagePullPolicy: Always
        image: {{ .Values.image.kibana }}
        ports:
        - containerPort: 5601
        volumeMounts:
        - mountPath: /usr/share/kibana/config/kibana.yml
          subPath: kibana.yml
          name: kibana-config
      - image: quay.io/gambol99/keycloak-proxy:v2.1.1
        name: proxy
        args:
          - --listen=0.0.0.0:8080
          - --discovery-url=https://keycloak.physical.edcop.io/auth/realms/kibana
          - --client-id=kibana
          - --client-secret=dcca6d49-f4fe-4ae2-8626-ad08e246dfb9
          - --redirection-url=https://keycloak.physical.edcop.io
          - --enable-refresh-tokens=true
          - --encryption-key=MsVRjD36bfAxfBvHUKUjXOTPXaItDThn  # 32 bytes string
          - --upstream-url=http://127.0.0.1:5601
          - --skip-openid-provider-tls-verify=true #needed until we have a PKI strategy
          - --resources=uri=/*
        volumeMounts:
        - mountPath: /etc/ssl/certs/
          name: k8s-certs
          readOnly: true

      volumes:
      - name: kibana-config
        configMap:
          name: {{ template "kibana.fullname" . }}-config
      - hostPath:
          path: /etc/kubernetes/pki
          type: DirectoryOrCreate
        name: k8s-certs
      restartPolicy: Always
      dnsPolicy: ClusterFirst
      nodeSelector:
        nodetype: {{ .Values.nodeSelector.nodetype }}
