# EDCOP Kibana Chart values
image:
  # Basic image: docker.elastic.co/kibana/kibana:6.3.0
  kibana: docker.elastic.co/kibana/kibana:6.3.0
networks:
  # Overlay is the name of the default cni network
  overlay: calico
nodeSelector:
  nodetype: master
ingress:
  # Enter the FQDN of your host
  host: kibana.physical.edcop.io  
